import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { GlobalProvider } from './Provider'

const jetBrainsFont = JetBrains_Mono({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${jetBrainsFont.style}`}>
				<GlobalProvider children={children} />
			</body>
		</html>
	)
}
